package models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.Serializable;

/**
 * Task model class
 */
@DynamoDBTable(tableName="tasks")
public class Task implements Serializable {
	public static class Status {
		public static final String INPROGRESS = "inprogress";
		public static final String DONE = "'done'";
	}

	private String id;
	private String message;
	private int urgency;
	private int importance;
	private String status;
	private String userID;

	public Task() {
	}
	public Task(String userID, String message, int importance, int urgency) {
		setImportance(importance);
		setUrgency(urgency);
		this.message = message;
		this.status = Status.INPROGRESS;
		this.userID = userID;
	}
	public Task(String userID, String message, int importance, int urgency, String status) {
		setImportance(importance);
		setUrgency(urgency);
		this.message = message;
		this.status = status;
		this.userID = userID;
	}

	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() { return id; }
	public void setId(String id) { this.id = id; }

	@DynamoDBAttribute(attributeName="message")
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}

	@DynamoDBAttribute(attributeName="urgency")
	public int getUrgency() {
		return this.urgency;
	}
	public void setUrgency(int urgency) {
		this.urgency = Math.min(Math.max(urgency, 0), 10);
	}

	@DynamoDBAttribute(attributeName="importance")
	public int getImportance() {
		return this.importance;
	}
	public void setImportance(int importance) {
		this.importance = Math.min(Math.max(importance, 0), 10);
	}

	@DynamoDBAttribute(attributeName="status")
	public String getStatus() {
		return this.status;
	}
	public void setStatus(String status) { this.status = status; }

	@DynamoDBAttribute(attributeName="userID")
	public String getUserID() { return userID; }
	public void setUserID(String userID) { this.userID = userID; }
}
